namespace Trivia.API.Enums;

public enum Category
{
    ANY = 0,
    GENERAL_KNOWLEDGE = 9,
    ENTERTAINMENT_BOOKS = 10,
    ENTERTAINMENT_FILM = 11,
    ENTERTAINMENT_MUSIC = 12,
    ENTERTAINMENT_MUSICAL_THEATRE = 13,
    ENTERTAINMENT_TV = 14,
    ENTERTAINMENT_VIDEO_GAMES = 15,
    ENTERTAINMENT_BOARD_GAMES = 16,
    ENTERTAINMENT_COMICS = 29,
    ENTERTAINMENT_ANIME = 31,
    ENTERTAINMENT_CARTOONS = 32,
    SCIENCE_NATURE = 17,
    SCIENCE_COMPUTERS = 18,
    SCIENCE_MATH = 19,
    SCIENCE_GADGETS = 30,
    MYTHOLOGY = 20,
    SPORTS = 21,
    GEOGRAPHY = 22,
    HISTORY = 23,
    POLITICS = 24,
    ART = 25,
    CELEBRITIES = 26,
    ANIMALS = 27,
    VEHICLES = 28
}
